### ISSUE TITLE
pysam not found in pileups conda environment

### ISSUE THREAD

**Issue by ayushm64** [mmolari/evo-genome-analysis#5]
When I try to run the snakemake workflow, it seems the pileups environment cannot find pysam. Here is the output I get when I try to run the workflow:

```

----------- loading config file -----------
--- run config:
{'input': 'test_data/input', 'output': 'test_data/output', 'pileups': {'RefWT113017-W': ['1eG_trimmed_WTRef_bow_sorted_collated', '1teG_trimmed_WTRef_bow_sorted_collated', '1tG_trimmed_WTRef_bow_sorted_collated', '2eG_trimmed_WTRef_bow_sorted_collated', '2teG_trimmed_WTRef_bow_sorted_collated', '2tG_trimmed_WTRef_bow_sorted_collated', '3eG_trimmed_WTRef_bow_sorted_collated', '3teG_trimmed_WTRef_bow_sorted_collated', '3tG_trimmed_WTRef_bow_sorted_collated', '4eG_trimmed_WTRef_bow_sorted_collated', '4teG_trimmed_WTRef_bow_sorted_collated', '4tG_trimmed_WTRef_bow_sorted_collated', 'E8G_trimmed_WTRef_bow_sorted_collated']}}

--- pileup
{'qual_min': 15, 'clip_minL': 100}

--- plots
{'coverage-maxbins': 2500, 'gaps': {'n-top-trajs': 33, 'freq-threshold': 0.75, 'coverage-threshold': 5, 'fwd-rev-noise-threshold': 0.2, 'fwd-rev-noise-tolerance': 0.05, 'max-initial-freq': 0.1}, 'consensus': {'n-top-trajs': 33, 'freq-threshold': 0.5, 'coverage-threshold': 5, 'fwd-rev-noise-threshold': 0.2, 'fwd-rev-noise-tolerance': 0.05, 'max-initial-freq': 0.1}, 'insertions': {'n-top-trajs': 33, 'freq-threshold': 0.5, 'coverage-threshold': 5, 'coverage-window': 100, 'coverage-fraction': 0.5, 'fwd-rev-noise-threshold': 0.2, 'fwd-rev-noise-tolerance': 0.05, 'max-initial-freq': 0.1}, 'clips': {'n-top-trajs': 33, 'freq-threshold': 0.5, 'coverage-threshold': 5, 'coverage-window': 100, 'coverage-fraction': 0.1, 'fwd-rev-noise-threshold': 0.2, 'fwd-rev-noise-tolerance': 0.05, 'max-initial-freq': 0.1}, 'supplementary': {'length-threshold': 50}, 'secondary': {'length-threshold': 50}}
-------------------------------------------


----------- run configuration ------------
input folder: test_data/input

output folder: test_data/output

pileups: {
  "RefWT113017-W": [
    "1eG_trimmed_WTRef_bow_sorted_collated",
    "1teG_trimmed_WTRef_bow_sorted_collated",
    "1tG_trimmed_WTRef_bow_sorted_collated",
    "2eG_trimmed_WTRef_bow_sorted_collated",
    "2teG_trimmed_WTRef_bow_sorted_collated",
    "2tG_trimmed_WTRef_bow_sorted_collated",
    "3eG_trimmed_WTRef_bow_sorted_collated",
    "3teG_trimmed_WTRef_bow_sorted_collated",
    "3tG_trimmed_WTRef_bow_sorted_collated",
    "4eG_trimmed_WTRef_bow_sorted_collated",
    "4teG_trimmed_WTRef_bow_sorted_collated",
    "4tG_trimmed_WTRef_bow_sorted_collated",
    "E8G_trimmed_WTRef_bow_sorted_collated"
  ]
}

reference records: {
  "RefWT113017-W": [
    "RefWTGD"
  ]
}
------------------------------------------
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                         count
------------------------  -------
all                             1
build_pileup                   13
extract_clip_counts             1
extract_counts                  1
extract_insertion_counts        1
extract_nonprimary             13
extract_unmapped               13
map_reads                      10
map_summary                    13
plot_clips                      1
plot_consensus                  1
plot_coverage                   1
plot_gaps                       1
plot_insertions                 1
plot_secondary                 13
plot_supplementary             13
total                          97

Select jobs to execute...
Execute 1 jobs...

[Sun Apr 21 08:48:20 2024]
localrule extract_nonprimary:
    input: test_data/output/mapped_reads/RefWT113017-W/4tG_trimmed_WTRef_bow_sorted_collated.bam
    output: test_data/output/pileup/RefWT113017-W/non_primary/4tG_trimmed_WTRef_bow_sorted_collated/non_primary.csv
    jobid: 54
    reason: Missing output files: test_data/output/pileup/RefWT113017-W/non_primary/4tG_trimmed_WTRef_bow_sorted_collated/non_primary.csv
    wildcards: ref_id=RefWT113017-W, sample_id=4tG_trimmed_WTRef_bow_sorted_collated
    resources: tmpdir=/tmp


        python3 scripts/pileup/extract_nonprimary.py             --bam test_data/output/mapped_reads/RefWT113017-W/4tG_trimmed_WTRef_bow_sorted_collated.bam --csv test_data/output/pileup/RefWT113017-W/non_primary/4tG_trimmed_WTRef_bow_sorted_collated/non_primary.csv

Activating conda environment: .snakemake/conda/e7058f7e8daa0d39e1ca146fe09d6f2d_
Traceback (most recent call last):
  File "/home/ayush/evo-genome-analysis/scripts/pileup/extract_nonprimary.py", line 1, in <module>
    import pysam
ModuleNotFoundError: No module named 'pysam'
[Sun Apr 21 08:48:21 2024]
Error in rule extract_nonprimary:
    jobid: 54
    input: test_data/output/mapped_reads/RefWT113017-W/4tG_trimmed_WTRef_bow_sorted_collated.bam
    output: test_data/output/pileup/RefWT113017-W/non_primary/4tG_trimmed_WTRef_bow_sorted_collated/non_primary.csv
    conda-env: /home/ayush/evo-genome-analysis/.snakemake/conda/e7058f7e8daa0d39e1ca146fe09d6f2d_
    shell:

        python3 scripts/pileup/extract_nonprimary.py             --bam test_data/output/mapped_reads/RefWT113017-W/4tG_trimmed_WTRef_bow_sorted_collated.bam --csv test_data/output/pileup/RefWT113017-W/non_primary/4tG_trimmed_WTRef_bow_sorted_collated/non_primary.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-04-21T084818.860925.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

I have tried manually activating the pileups environment, installing pysam 0.20.0 using conda, and running conda list within the environment. pysam 0.20.0 shows up within the package list, but i still get the same error. What could be causing this?

**Comment by mmolari** [comment]
Hi @ayushm64, I saw the issue is already closed but mentioning this here just in case...

I have two guesses, but I am not actually sure what is the issue.
- The first guess is that the `--use-conda` flag is missing in the snakemake command. This should be automatically set when using the `local` profile. However I do not think this is the case, since from your log it seems that snakemake is activating conda environments.
- The second is that maybe it has something to do with snakemake version? I developed this pipeline for snakemake v7, and I think the new version 8 has some breaking changes. I'll add a line in the readme and investigate further.

Have a nice day!
Marco

**Comment by ayushm64** [comment]
Thank you for the response, Marco! It seems I've closed the issue too soon, however; with snakemake 8, the workflow fails while executing the extract_nonprimary rule. When I installed snakemake v7.32.4 and ran the workflow again after your response, the ModuleNotFoundError was explicitly invoked for pysam at the extract_nonprimary rule. I am attaching the log files, if they may be of any use to you. The first was run with a snakemake 8 environment activated, the second with 7.32.4. 

[2024-04-22T205905.182869.snakemake.log](https://github.com/mmolari/evo-genome-analysis/files/15070161/2024-04-22T205905.182869.snakemake.log)
[2024-04-22T212117.567753.snakemake.log](https://github.com/mmolari/evo-genome-analysis/files/15070162/2024-04-22T212117.567753.snakemake.log)

**Comment by ayushm64** [comment]
I may have some more useful information. It seems pysam is not installed in the pileups conda environment, and I think the reason may be that bioconda does not yet support python 3.11, and the python installed in the pileups environment is 3.11.

**Comment by mmolari** [comment]
Hi @ayushm64,

Thank you for your feedback!

Concerning the python version the pileup environment should have [python 3.10](https://github.com/mmolari/evo-genome-analysis/blob/79d448983ba5cf2e338ae1e10cc532df9a580760/conda_envs/pileup.yml#L12).
I tried creating the pileups environment from scratch with the command:
```sh
mamba env create -n test -f conda_envs/pileup.yml
```
And indeed if I list the packages installed I have both `python=3.10.8` and `pysam=0.20.0`, so I seem to be not able to reproduce the issue...

At this point my guesses is that it might be due to either of these:
- different conda settings? I am using conda version 24.1.2 and mamba version 1.5.7. If you run the pipeline with `--profile local` setting then the [frontend will default to mamba](https://github.com/mmolari/evo-genome-analysis/blob/79d448983ba5cf2e338ae1e10cc532df9a580760/local/config.yaml#L3)
- Another thing I have not tested for is other architectures/operating systems. I am working on linux, I am not sure if this would work for a mac for example.

A thing that might solve it for sure is if you re-create the environment on your machine, and substitute the `pileup.yml` file.
This would amount to [creating a new environment with](https://github.com/mmolari/evo-genome-analysis/blob/main/notes/workflow_structure.md#conda-environments):
```sh
mamba create -n pileup -c bioconda -c conda-forge minimap2 samtools pysam biopython pandas
```
And then activate it and export it in a yml file, and substitute it to the pileup file:
```sh
conda activate pileup
conda env export --no-builds > pileup.yml
```

I hope this helps!

Marco

**Comment by ayushm64** [comment]
Hi Marco,

Recreating the pileups environment from scratch is working. However, my workflow is still failing at the extract non-primary rule step. I manually activated the pileups environment and ran the extract_nonprimary.py script with some modifications (just printing things to the terminal) to help me debug, and it seems like the csv files are not being generated because none of my BAM files contain secondary or supplementary alignments. The workflow then stops and raises a MissingOutputException. How do I get around this?

**Comment by mmolari** [comment]
Mmmmh good point, I should make sure that the case in which no secondary/supplementary mappings are present is still dealt with correctly...
In the meantime you can comment out the requests for these files in the rules:
- [for the non-primary reads](https://github.com/mmolari/evo-genome-analysis/blob/310edf6efe4b4fe0537c722608ea54cbaf2dca0b/rules/pileup.smk#L195C1-L198C11)
- [for the non-primary figures](https://github.com/mmolari/evo-genome-analysis/blob/310edf6efe4b4fe0537c722608ea54cbaf2dca0b/rules/plots.smk#L228C1-L235C11)

This should prevent these rules from executing. Otherwise you can also execute with the flag `--keep-going`, which should execute the other rules even if some are failing.

**Comment by ayushm64** [comment]
This worked perfectly, thank you so much for your help Marco!!
